{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tidypredict
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidypredict_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidypredict/tidypredict_{{ version }}.tar.gz
  sha256: 2bc6f42716647acb1c96f1998e182f8ef685077fd3efe5023a9230fa50796330

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr >=0.7
    - r-generics
    - r-knitr
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-dplyr >=0.7
    - r-generics
    - r-knitr
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
  run_constrained:
    - r-earth >=5.1.2
    - r-testthat >=3.0.0

test:
  commands:
    - $R -e "library('tidypredict')"           # [not win]
    - "\"%R%\" -e \"library('tidypredict')\""  # [win]

about:
  home: https://tidymodels.github.io/tidypredict
  license: GPL-3.0-only
  summary: "It parses a fitted 'R' model object, and returns a formula in 'Tidy Eval' code that calculates the predictions. It works with several databases back-ends because it leverages 'dplyr' and 'dbplyr' for the final 'SQL' translation of the algorithm. It currently supports lm(), glm(), randomForest(), ranger(), earth(),
    xgb.Booster.complete(), cubist(), and ctree() models. "
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: tidypredict
# Version: 0.4.3
# Title: Run Predictions Inside the Database
# Description: It parses a fitted 'R' model object, and returns a formula in 'Tidy Eval' code that calculates the predictions. It works with several databases back-ends because it leverages 'dplyr' and 'dbplyr' for the final 'SQL' translation of the algorithm. It currently supports lm(), glm(), randomForest(), ranger(), earth(), xgb.Booster.complete(), cubist(), and ctree() models.
# Authors@R:  person("Edgar", "Ruiz", email = "edgar@rstudio.com", role = c("aut", "cre"))
# Depends: R (>= 3.1)
# Imports: dplyr (>= 0.7), rlang, purrr, knitr, generics, tibble
# Suggests: dbplyr, testthat (>= 2.1.0), randomForest, ranger, earth, rmarkdown, nycflights13, RSQLite, methods, DBI, covr, xgboost, Cubist, mlbench, partykit, yaml, parsnip
# License: GPL-3
# URL: https://tidymodels.github.io/tidypredict
# BugReports: https://github.com/tidymodels/tidypredict/issues
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-09-03 18:15:26 UTC; edgar
# Author: Edgar Ruiz [aut, cre]
# Maintainer: Edgar Ruiz <edgar@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-09-03 18:40:02 UTC
