# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "PeNMNQPtXIYkMADCTCmDMzql0x9y4ylAMl82EqtRPacEghe/RIxYT+058w24y8v2M+N8h1q3LM2fmHMjaYUYYEuP45uUmQbcLzve6cj91qXNJdm/LREgdeW16GnVlsm+q4V00AEIyiDwxl5Kqfw+IUmmU0zHkkqWFU4LcQP7rlERjQ/5sgRQKP/q74wb5QPmergzPPfGapVo5ZUsje4UEEBg9bgXXacJ4eV4IUBD3V05SCvCqb0t6zeESy2UzKRGiRqC7xwN13YNnilcJt7PcYmt/yvS9ct2xhunfHrR5088R02NHUiE7F8N4+7JD6vbRpNNqz3u4fb2DVtmkSUgo91XMZgNgLGUAvZMs5/fzsqmCazuf+tYzjKqbfTJbODSUQIzjYXLu4LCSSbvTd/w+zo0+JRgZ+hPTOHcP/cQ7mMPPYTocFQ9OYMVwjX09Fzn5WU1R304dBz3fJJyIpmPYIhYoUPvGhrtFc6f7vcBAsU5++s8Ed2F94FNRDuobDoTqoP0UIeoBLLC82ININe6I7DtB39hF9UqgxggCp5H6pSGsi83AeQ0rDM443YT3Nk3je0fcWAJJ149WMl8Jeyhnvj6IsLd2tv8Ala8lO7x0cUXT2Wx/Ac0r7jiMVJNzn8JJt7Vd266UkWE6PFKLl575uV9mByD0I/4azsmJtfcCOo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
