travis:
  secure:
    BINSTAR_TOKEN: PeNMNQPtXIYkMADCTCmDMzql0x9y4ylAMl82EqtRPacEghe/RIxYT+058w24y8v2M+N8h1q3LM2fmHMjaYUYYEuP45uUmQbcLzve6cj91qXNJdm/LREgdeW16GnVlsm+q4V00AEIyiDwxl5Kqfw+IUmmU0zHkkqWFU4LcQP7rlERjQ/5sgRQKP/q74wb5QPmergzPPfGapVo5ZUsje4UEEBg9bgXXacJ4eV4IUBD3V05SCvCqb0t6zeESy2UzKRGiRqC7xwN13YNnilcJt7PcYmt/yvS9ct2xhunfHrR5088R02NHUiE7F8N4+7JD6vbRpNNqz3u4fb2DVtmkSUgo91XMZgNgLGUAvZMs5/fzsqmCazuf+tYzjKqbfTJbODSUQIzjYXLu4LCSSbvTd/w+zo0+JRgZ+hPTOHcP/cQ7mMPPYTocFQ9OYMVwjX09Fzn5WU1R304dBz3fJJyIpmPYIhYoUPvGhrtFc6f7vcBAsU5++s8Ed2F94FNRDuobDoTqoP0UIeoBLLC82ININe6I7DtB39hF9UqgxggCp5H6pSGsi83AeQ0rDM443YT3Nk3je0fcWAJJ149WMl8Jeyhnvj6IsLd2tv8Ala8lO7x0cUXT2Wx/Ac0r7jiMVJNzn8JJt7Vd266UkWE6PFKLl575uV9mByD0I/4azsmJtfcCOo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
