appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: liCvnb2Ng2QCtEGfd5gZUpt0TFTDVnMB5BD7el+M0he0gxwJUGE2LmRIYhbJOhEA+DJ5NjSHrrEUcGYIKhJRdrsZV+OeL7AdzRgBi7xX2OvPOYzbGVNp27RgtCytpk6h6uYETEDGT6Oykuy3n25SSFx/+xOguKkSBe7/aTUjcaS25LK4nJkr1GSi8b724TWrX2Rz7h8RsN+oG10ZPZbvbTBSooDExiFg/CZBwZXyjAmn+o662jZkrWgGbeelC4AqhqMTVHj5PEyH61DybYFBsUfckFVyNUgE444l+6esS21hlzUX7SBJoQOuGrVoKANlWfyHNdreYZN2EkXoHTa1gDLhlKdoGCd0wB6hTDeQ0vuqgypMZ6buOBz+DV/dJxFLF+zI07uvbE+nbaLVjrnoDtaIbmMez43MF9Kjd8dFMoh2eHPsJxIicGVVGm/CKxP03yAOw+czFC1Mzp6Qlxo/vw3UI2dRS/njxsdIu+Usbmtc0bE7FNY5s6PpjOX4ITACwTNl/m81bfRSvKLUvmYiWsRU981gNPjW7deK7l+ZTuBRYLoOnYQiEIt/AxffWVuRwyikAXiRQKWQQktbaULvNMEC7NEhIsqBlTphd8aZfzcYpDZJxuRK2bV3KzfkIJ8q+lsf908UOE8LCjfMA8GbUaONya4I2fiqPOYlscBt9Q4=}
bot:
  automerge: true
