travis:
  secure:
    BINSTAR_TOKEN: eDN50uzUvzhnhH2UInu2f4VnseLPpOG02T9Ma0cI9sY2u02ij4h/gHt3tyVpgeCU/cMy6yVrKFYLqT2NOG1VAY/1n7axXWeHLARbDgxhL75RJT/EtBchMRfiIgH6m+Wti2fijwn3B5hd/lLZ+QzmfGJWG0b+LQiNQNkJV/5yPkDR6o/kF5oMG2o9TqDVM9+Z40vuwA71hOgsS5JApzBFPFn4ICrMjoUdKmf2AZM/p7WMl/jgroScUVckWgVd0O2GNjdOazCkLHwHYcs+EwlG5Ef6oSMg+eNpOLSIO3AdMGa0t/7FCHtatG4OhlfDLFzdDJAE4ImwYxwKK1G8d+M5pDemFM/BX3O6pb7XqRtmFLSr911WyCgB0rVhcvdN8uor1quD4hg+m9QOXrA2cY40U0CTxkqFiLOm1xCXijt32uwBFxXOrGaMitd2J9jjYBd3hokrnqvs9EbHVY0dawmuVod2Ta8jNfYJA042icqysP6Ejppk1ChJrMbb7sp73G/YlAWJvdXkpvd1m4CysLSXN1Meqbs3s8n/EkEDKez84D9FghYmJBfKNNMmAkaM3czwJFHdZ7nPEZL6tG8R9Zf2PDh1nNaAatoEfxM9EmJCwM6L8ac1wM8Fcj8OorZYZFPXDUyF2Taweziqv1fe610+W7wV2FpmIGeeex16l2NhRjs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
